export const promotionInfo = {
  code: 'MEOXINH10',
  discountPercent: 10,
  title: 'Ưu Đãi Đặc Biệt: Giảm 10% Toàn Bộ Dịch Vụ',
  subtitle: 'Áp dụng tự động cho mọi gói dịch vụ lưu trú, spa và chăm sóc khi đặt lịch trực tuyến.',
  bannerTag: '🔥 HOT PROMOTION • GIẢM NGAY 10%',
  expiryDate: 'Áp dụng cho mọi lịch đặt trong tháng',
};

export const packagesList = [
  { 
    id: 'p1', 
    category: 'Lưu trú',
    name: 'Gói Tiết Kiệm', 
    originalPrice: 200000, 
    price: 180000, 
    originalPriceString: '200.000đ', 
    priceString: '180.000đ', 
    discountPercent: 10,
    discountBadge: '-10%',
    savingsString: '20.000đ',
    period: '/ngày', 
    bg: 'bg-[#FFF9F0]', 
    border: 'border-orange-100', 
    desc: 'Ăn uống cơ bản, phòng riêng tiêu chuẩn khử khuẩn và dọn dẹp hàng ngày', 
    image: '/images/service_hotel.png', 
    features: ['Phòng tiêu chuẩn ấm cúng', 'Cho ăn theo lịch khoa học', 'Vệ sinh, dọn dẹp hàng ngày', 'Theo dõi sức khỏe cơ bản'],
    isPromo: true
  },
  { 
    id: 'p2', 
    category: 'Lưu trú',
    name: 'Gói Tiêu Chuẩn', 
    originalPrice: 250000, 
    price: 225000, 
    originalPriceString: '250.000đ', 
    priceString: '225.000đ', 
    discountPercent: 10,
    discountBadge: '-10%',
    savingsString: '25.000đ',
    period: '/ngày', 
    bg: 'bg-primary-light', 
    border: 'border-green-100', 
    desc: 'Bao gồm pate cao cấp, phòng rộng rãi thoáng mát và giờ vui chơi', 
    image: '/images/service_hotel.png', 
    features: ['Phòng rộng rãi riêng tư', 'Pate dinh dưỡng cao cấp', 'Vệ sinh khử khuẩn chu đáo', 'Theo dõi sức khỏe & giờ chơi'],
    isPromo: true,
    isPopular: true
  },
  { 
    id: 'p3', 
    category: 'Lưu trú',
    name: 'Gói Cao Cấp', 
    originalPrice: 350000, 
    price: 315000, 
    originalPriceString: '350.000đ', 
    priceString: '315.000đ', 
    discountPercent: 10,
    discountBadge: '-10%',
    savingsString: '35.000đ',
    period: '/ngày', 
    bg: 'bg-primary-light', 
    border: 'border-green-100', 
    desc: 'Spa grooming miễn phí 1 lần, camera 24/7 theo dõi bé yêu trực tiếp', 
    image: '/images/service_spa.png', 
    features: ['Phòng rộng rãi view đẹp', 'Pate cao cấp & snack', 'Camera 24/7 theo dõi trực tiếp', 'Spa chải lông cơ bản miễn phí'],
    isPromo: true
  },
  { 
    id: 'p4', 
    category: 'Spa - Tắm cắt',
    name: 'Gói VIP Toàn Diện', 
    originalPrice: 500000, 
    price: 450000, 
    originalPriceString: '500.000đ', 
    priceString: '450.000đ', 
    discountPercent: 10,
    discountBadge: '-10%',
    savingsString: '50.000đ',
    period: '/ngày', 
    bg: 'bg-[#FFF9F0]', 
    border: 'border-orange-100', 
    desc: 'Phòng VIP lớn, chế độ ăn organic, massage mỗi ngày và spa trọn gói', 
    image: '/images/service_care.png', 
    features: ['Phòng VIP biệt lập', 'Chế độ ăn organic cao cấp', 'Massage thư giãn mỗi ngày', 'Theo dõi sức khỏe & camera 24/7', 'Spa/Tắm cắt tỉa (1 lần)'],
    isPromo: true,
    isBestChoice: true
  },
  { 
    id: 's1', 
    category: 'Spa - Tắm cắt',
    name: 'Combo Spa & Tắm Cắt Chuẩn Salon', 
    originalPrice: 220000, 
    price: 198000, 
    originalPriceString: '220.000đ', 
    priceString: '198.000đ', 
    discountPercent: 10,
    discountBadge: '-10%',
    savingsString: '22.000đ',
    period: '/lần', 
    bg: 'bg-[#FFF9F0]', 
    border: 'border-orange-100', 
    desc: 'Tắm dưỡng lông mượt mà, cắt mài móng, vệ sinh tai mắt và tạo phom dáng', 
    image: '/images/service_spa.png', 
    features: ['Tắm bọt nano khử khuẩn', 'Vệ sinh tai, mắt & tuyến hôi', 'Cắt mài móng an toàn', 'Sấy tạo phom lông mềm mại'],
    isPromo: true
  },
  { 
    id: 's2', 
    category: 'Dịch vụ khác',
    name: 'Dịch Vụ Đưa Đón & Y Tế Tận Nơi', 
    originalPrice: 150000, 
    price: 135000, 
    originalPriceString: '150.000đ', 
    priceString: '135.000đ', 
    discountPercent: 10,
    discountBadge: '-10%',
    savingsString: '15.000đ',
    period: '/chuyến', 
    bg: 'bg-primary-light', 
    border: 'border-green-100', 
    desc: 'Đưa đón bé mèo tận nhà bằng xe chuyên dụng an toàn, kiểm tra sức khỏe ban đầu', 
    image: '/images/service_care.png', 
    features: ['Xe đưa đón có máy lạnh', 'Lồng chuyên dụng êm ái', 'Kiểm tra cân nặng & thân nhiệt', 'Cập nhật lộ trình theo thời gian thực'],
    isPromo: true
  }
];
