export const promotionInfo = {
  code: 'THANTHIET10',
  secondaryCode: 'MEOXINH10',
  discountPercent: 10,
  title: 'Ưu Đãi Tri Ân: Giảm 10% Khi Sử Dụng Dịch Vụ Lần 2',
  subtitle: 'Dành riêng cho khách hàng thân thiết quay lại đặt dịch vụ lưu trú & spa cho bé mèo.',
  bannerTag: '🎁 TRI ÂN KHÁCH HÀNG • GIẢM 10% LẦN 2',
  expiryDate: 'Áp dụng tự động cho lần đặt thứ 2 trở đi',
  terms: 'Ưu đãi được kích hoạt tự động ngay khi bạn đã hoàn tất ít nhất 1 lần đặt dịch vụ trước đó.'
};

export const packagesList = [
  { 
    id: 'p1', 
    category: 'Lưu trú',
    name: 'Gói Mèo Quý Tộc', 
    originalPrice: 200000, 
    price: 180000, 
    originalPriceString: '200.000đ', 
    priceString: '180.000đ', 
    discountPercent: 10,
    discountBadge: 'Lần 2: -10%',
    savingsString: '20.000đ',
    period: '/ngày', 
    bg: 'bg-[#FFF9F0]', 
    border: 'border-orange-100', 
    desc: 'Phòng Deluxe sang trọng, menu 3 bữa chính + 1 bữa phụ đa dạng, camera riêng 24/24 với thoại 2 chiều.', 
    image: '/images/rooms/deluxe-1.png', 
    features: [
      'Phòng Deluxe cao cấp (2 biến thể)',
      '3 bữa chính + 1 bữa phụ (sen tự chọn menu)',
      'Cát đậu nành hữu cơ — dọn 2 lần/ngày',
      'Camera riêng 24/24, chỉnh hướng, thoại 2 chiều',
      'Tắm miễn phí khi gửi từ 5 ngày',
      'Free đón trả trong vòng 8km'
    ],
    isPromo: true,
    isBestChoice: true
  },
  { 
    id: 'p2', 
    category: 'Lưu trú',
    name: 'Gói Mèo Sang Chảnh', 
    originalPrice: 150000, 
    price: 135000, 
    originalPriceString: '150.000đ', 
    priceString: '135.000đ', 
    discountPercent: 10,
    discountBadge: 'Lần 2: -10%',
    savingsString: '15.000đ',
    period: '/ngày', 
    bg: 'bg-primary-light', 
    border: 'border-green-100', 
    desc: 'Phòng VIP ấm cúng, 3 bữa/ngày full pate hoặc mix hạt, camera riêng 24/24 theo dõi bé.', 
    image: '/images/rooms/vip.png', 
    features: [
      'Phòng VIP (nâng VVIP +10k, Deluxe +20k)',
      'Ăn 3 bữa/ngày: full pate hoặc mix 1 bữa hạt',
      'Cát khoáng Bentonite — dọn 1 lần/ngày',
      'Camera trong phòng riêng 24/24',
      'Tắm miễn phí khi gửi từ 7 ngày',
      'Free đón trả trong vòng 6km'
    ],
    isPromo: true,
    isPopular: true
  },
  { 
    id: 'p3', 
    category: 'Lưu trú',
    name: 'Gói Mèo Thượng Đế', 
    originalPrice: 120000, 
    price: 108000, 
    originalPriceString: '120.000đ', 
    priceString: '108.000đ', 
    discountPercent: 10,
    discountBadge: 'Lần 2: -10%',
    savingsString: '12.000đ',
    period: '/ngày', 
    bg: 'bg-primary-light', 
    border: 'border-green-100', 
    desc: 'Phòng VIP, ăn 3 bữa/ngày 1 pate + 2 hạt, cập nhật tình hình hàng ngày. Có thể thêm camera +10k.', 
    image: '/images/rooms/vip.png', 
    features: [
      'Phòng VIP (nâng VVIP +10k, Deluxe +20k)',
      'Ăn 3 bữa/ngày: 1 pate + 2 hạt',
      'Cát khoáng Bentonite — dọn 1 lần/ngày',
      'Cập nhật tình hình hàng ngày (camera +10k)',
      'Tắm miễn phí khi gửi từ 8 ngày',
      'Free đón trả trong vòng 5km'
    ],
    isPromo: true
  },
  { 
    id: 'p4-tt', 
    category: 'Lưu trú',
    name: 'Gói Mèo Tự Túc', 
    originalPrice: 90000, 
    price: 81000, 
    originalPriceString: '90.000đ', 
    priceString: '81.000đ', 
    discountPercent: 10,
    discountBadge: 'Lần 2: -10%',
    savingsString: '9.000đ',
    period: '/ngày', 
    bg: 'bg-[#FFF9F0]', 
    border: 'border-orange-100', 
    desc: 'Sen tự chuẩn bị đồ ăn, tối đa 3 bữa/ngày. Phòng VIP sạch sẽ, cập nhật tình hình mỗi ngày.', 
    image: '/images/rooms/vip.png', 
    features: [
      'Phòng VIP (nâng VVIP +10k, Deluxe +20k)',
      'Sen tự chuẩn bị đồ ăn — tối đa 3 bữa/ngày',
      'Cát khoáng Bentonite — dọn 1 lần/ngày',
      'Cập nhật tình hình hàng ngày (camera +10k)',
      'Free đón trả trong vòng 4km'
    ],
    isPromo: true
  },
  {
    id: 'spa1',
    category: 'Spa - Tắm cắt',
    name: 'Tạo Kiểu Mèo',
    originalPrice: 110000,
    price: 99000,
    originalPriceString: 'từ 110.000đ',
    priceString: 'từ 99.000đ',
    discountPercent: 10,
    discountBadge: 'Lần 2: -10%',
    savingsString: '11.000đ',
    period: '/lần',
    bg: 'bg-[#FFF9F0]',
    border: 'border-orange-100',
    desc: 'Tạo kiểu mèo chuyên nghiệp (chưa gồm combo tắm sấy). Giá theo cân nặng bé.',
    image: '/images/service_spa.png',
    features: [
      'Cạo sơ (lộ lông đầu + 4 bốt chân + chôm đuôi/cà đuôi): <5kg 110K | 5–10kg 150K | ≥10kg 200K',
      'Cạo + cắt tạo hình (Khủng long, trái tim,...): <5kg 200K | 5–10kg 250K | ≥10kg 280K',
      'Chưa bao gồm dịch vụ tắm sấy',
    ],
    isPromo: true,
  },
  {
    id: 'spa2',
    category: 'Spa - Tắm cắt',
    name: 'Cắt Tỉa Mèo — Combo 8 Bước',
    originalPrice: 300000,
    price: 270000,
    originalPriceString: 'từ 300.000đ',
    priceString: 'từ 270.000đ',
    discountPercent: 10,
    discountBadge: 'Lần 2: -10%',
    savingsString: '30.000đ',
    period: '/lần',
    bg: 'bg-primary-light',
    border: 'border-green-100',
    desc: 'Cắt ngắn lông theo combo 8 bước chuẩn salon, bo gọn bằng kéo hoặc tông đơ còn 0,5–1cm.',
    image: '/images/service_spa.png',
    features: [
      'Bo gọn ít bằng kéo hoặc đầy ngắn bằng tông đơ còn 0,5–1cm lông',
      'Giá: <5kg 300K | 5–10kg 350K | ≥10kg 400K',
      'Combo 8 bước chăm sóc toàn diện',
    ],
    isPromo: true,
    isPopular: true,
  },
  {
    id: 'spa3',
    category: 'Spa - Tắm cắt',
    name: 'Combo Tắm Sấy Mèo',
    originalPrice: 120000,
    price: 108000,
    originalPriceString: 'từ 120.000đ',
    priceString: 'từ 108.000đ',
    discountPercent: 10,
    discountBadge: 'Lần 2: -10%',
    savingsString: '12.000đ',
    period: '/lần',
    bg: 'bg-[#FFF9F0]',
    border: 'border-orange-100',
    desc: 'Tắm + Vệ sinh tai + Cắt móng. Giá theo cân nặng và độ dài lông bé mèo.',
    image: '/images/service_spa.png',
    features: [
      'Bao gồm: Tắm, vệ sinh tai & cắt móng',
      'Lông ngắn: <5kg 120K | 5–10kg 140K | ≥10kg 160K',
      'Lông dài: <5kg 140K | 5–10kg 160K | ≥10kg 180K',
    ],
    isPromo: true,
  },
  { 
    id: 's2', 
    category: 'Dịch vụ khác',
    name: 'Dịch Vụ Đưa Đón & Y Tế Tận Nơi', 
    originalPrice: 150000, 
    price: 135000, 
    originalPriceString: '150.000đ', 
    priceString: '135.000đ', 
    discountPercent: 10,
    discountBadge: 'Lần 2: -10%',
    savingsString: '15.000đ',
    period: '/chuyến', 
    bg: 'bg-primary-light', 
    border: 'border-green-100', 
    desc: 'Đưa đón bé mèo tận nhà bằng xe chuyên dụng an toàn, kiểm tra sức khỏe ban đầu', 
    image: '/images/service_care.png', 
    features: ['Xe đưa đón có máy lạnh', 'Lồng chuyên dụng êm ái', 'Kiểm tra cân nặng & thân nhiệt', 'Cập nhật lộ trình theo thời gian thực'],
    isPromo: true
  }
];
